#!/bin/bash
clock=/home/ysh/project/libraries/cm3/src/stm32f10x_rcc.c
clockh=/home/ysh/project/libraries/cm3/inc/stm32f10x_rcc.h

nvic=gpio=/home/ysh/project/libraries/cm3/src/stm32f10x_nvic.c
nvich=gpio=/home/ysh/project/libraries/cm3/inc/stm32f10x_nvic.h

gpio=/home/ysh/project/libraries/cm3/src/stm32f10x_gpio.c
gpioh=/home/ysh/project/libraries/cm3/inc/stm32f10x_gpio.h

case $1 in
	clock)
		vim $clock
		break;
		;;
	clockh)
		vim $clockh
		break;
		;;
esac
		
		
		
